#!/usr/bin/env python3
"""
Surgical cmake output pre/post-processor for WSL2 Android builds.

Problem: cmake.exe (Windows) writes W:\home\... paths. Some files are read by
the JVM (needs Linux /home/... paths), others by ninja.exe/clang.exe (needs
W:\ paths).

Prefab cmake config files are generated by AGP's prefab tool with Linux /home/
paths.  cmake.exe reads them and propagates the Linux paths verbatim into
build.ninja as -isystem flags, making clang.exe unable to find headers.

Usage:
  python3 fix_cmake_paths.py --pre <build_dir>   # BEFORE cmake.exe runs
  python3 fix_cmake_paths.py <build_dir>          # AFTER cmake.exe runs

Pre-processing (--pre):
  Prefab cmake config files in <build_dir>/../../prefab/<abi>:
    - ALL /home/, /tmp/ etc. paths -> W:/home/ (cmake.exe needs Windows paths)

Post-processing (default):
  android_gradle_build.json:
    - buildTargetsCommandComponents[]."-C" arg: KEEP W:\ (ninja.exe reads this)
    - cleanCommandsComponents[]."-C" arg:       KEEP W:\ (ninja.exe reads this)
    - libraries[].output:                       -> Linux (JVM reads .so path)
    - libraries[].runtimeFiles:                 -> Linux (JVM reads .so paths)
    - buildFiles:                               -> Linux (JVM reads CMakeLists.txt paths)

  compile_commands.json:
    - ALL paths -> Linux (AGP reads for source-to-object mapping)
    - command field: ALL paths -> Linux, backslashes -> /

  .cmake/api/v1/reply/*.json:
    - ALL paths -> Linux (AGP reads for target/source info)

  build.ninja:
    - backslash path separators -> / (AGP target regex needs forward slashes)
    - W:/ paths KEPT (ninja.exe/clang.exe need Windows paths for -isystem)

  CMakeCache.txt, cmake_install.cmake:
    - DO NOT TOUCH (used by cmake.exe, need W:\ paths)
"""
import os, re, sys, json

# Pattern: matches W:\ or W:/ or bare \\home\\ style paths
W_PATH_RE = re.compile(
    rb'W:[/\\]+(?=home|tmp|root|opt)'
    rb'|\\\\home\\\\'
    rb'|\\\\tmp\\\\'
)

def linux_to_win(s: str) -> str:
    """Convert a Linux /home/, /tmp/, /root/ path to W:/ Windows path.

    Used to pre-process prefab cmake config files so that cmake.exe (Windows)
    writes Windows-compatible -isystem paths into build.ninja.
    """
    s = re.sub(r'(?<![A-Za-z]:)/home/', 'W:/home/', s)
    s = re.sub(r'(?<![A-Za-z]:)/tmp/', 'W:/tmp/', s)
    s = re.sub(r'(?<![A-Za-z]:)/root/', 'W:/root/', s)
    s = re.sub(r'(?<![A-Za-z]:)/opt/', 'W:/opt/', s)
    return s


def preprocess_prefab_cmake(build_dir: str):
    """Pre-process prefab cmake config files BEFORE cmake.exe runs.

    The prefab tool (JVM) generates cmake config files with Linux /home/ paths.
    cmake.exe reads these and propagates them verbatim into build.ninja as
    -isystem flags. clang.exe (Windows) can't access /home/ paths; they need
    W:/home/ paths (via the W: drive mapping to \\wsl.localhost\\Ubuntu).

    Prefab cmake files are at: <build_dir>/../../prefab/<abi>/...
    """
    abi = os.path.basename(build_dir)
    hash_dir = os.path.dirname(build_dir)
    prefab_cmake_dir = os.path.join(hash_dir, 'prefab', abi)
    if not os.path.isdir(prefab_cmake_dir):
        print(f'  Pre: no prefab cmake dir at {prefab_cmake_dir}')
        return

    fixed = []
    for root, dirs, files in os.walk(prefab_cmake_dir):
        for fn in files:
            if fn.endswith('.cmake'):
                fp = os.path.join(root, fn)
                raw = open(fp, 'rb').read()
                text = raw.decode('utf-8', errors='replace')
                fixed_text = linux_to_win(text)
                if fixed_text != text:
                    open(fp, 'wb').write(fixed_text.encode('utf-8'))
                    fixed.append(os.path.relpath(fp, hash_dir))

    if fixed:
        print(f'  Pre-fixed cmake: {", ".join(fixed)}')
    else:
        print(f'  Pre: no cmake changes needed')


def win_to_linux(s: str) -> str:
    """Convert a single Windows path string to Linux path."""
    # W:/home/... or W:\home\...
    s = re.sub(r'W:[/\\]+home[/\\]+', '/home/', s)
    s = re.sub(r'W:[/\\]+tmp[/\\]+', '/tmp/', s)
    s = re.sub(r'W:[/\\]+root[/\\]+', '/root/', s)
    # bare \\home\\ (W: already stripped but separators remain)
    s = re.sub(r'\\\\home\\\\', '/home/', s)
    s = re.sub(r'\\\\tmp\\\\', '/tmp/', s)
    # fix remaining backslash separators in paths that start with /home/ etc.
    if '/home/' in s or '/tmp/' in s or '/root/' in s:
        s = s.replace('\\\\', '/').replace('\\', '/')
    return s

def fix_string_value(v: str) -> str:
    if isinstance(v, str):
        return win_to_linux(v)
    return v

def fix_list(lst):
    return [fix_string_value(x) if isinstance(x, str) else x for x in lst]

def fix_agb(data: dict) -> dict:
    """Fix android_gradle_build.json with field-aware logic."""
    result = dict(data)

    # buildFiles: list of CMakeLists.txt paths -> Linux
    if 'buildFiles' in result:
        result['buildFiles'] = fix_list(result['buildFiles'])

    # libraries: fix output and runtimeFiles -> Linux, leave rest
    if 'libraries' in result:
        libs = {}
        for lib_id, lib in result['libraries'].items():
            lib = dict(lib)
            if 'output' in lib:
                lib['output'] = fix_string_value(lib['output'])
            if 'runtimeFiles' in lib:
                lib['runtimeFiles'] = fix_list(lib['runtimeFiles'])
            libs[lib_id] = lib
        result['libraries'] = libs

    # buildTargetsCommandComponents: keep W:\ for the -C build_dir arg
    # but fix any artifact/source paths that might appear after the build target
    # Format: [ninja_path, "-C", build_dir_W, ...targets...]
    # We want to keep the build_dir_W as-is for ninja.exe

    # cleanCommandsComponents: same — keep -C build_dir as W:\
    # (no change needed for these two fields)

    return result

def fix_command_field(cmd: str) -> str:
    """Normalise all paths in a compile_commands.json command string.

    compile_commands.json is used by AGP and IDE tools for analysis only — the
    actual compilation is done by ninja.exe reading build.ninja.  So we can
    safely convert ALL paths to Linux format here.

    1. Convert W:/home/, W:\\home\\ absolute Windows paths -> Linux /home/
    2. Convert remaining backslash separators -> /
    """
    cmd = win_to_linux(cmd)
    if '\\' in cmd:
        cmd = cmd.replace('\\', '/')
    return cmd


def fix_compile_commands(data: list) -> list:
    """Fix compile_commands.json — all paths to Linux for AGP source matching."""
    result = []
    for entry in data:
        e = dict(entry)
        for key in ('directory', 'file', 'output'):
            if key in e:
                e[key] = win_to_linux(e[key])
        # Also normalise the 'command' field so AGP's target-extraction regex
        # (which requires CMakeFiles/<target>.dir/ with forward slashes) works.
        if 'command' in e:
            e['command'] = fix_command_field(e['command'])
        result.append(e)
    return result

def normalize_str(v: str) -> str:
    """Normalize a single string value from a cmake File API JSON.

    Steps:
    1. Convert absolute W:\\ / W:/ paths to Linux /home/, /tmp/, /root/
    2. Convert ALL remaining backslash path separators to forward slashes
       (cmake File API strings are file paths or identifiers — no legitimate
        non-path backslashes exist in these files)
    """
    v = win_to_linux(v)
    # After absolute-path conversion, convert any remaining backslash
    # separators (relative paths like CMakeFiles\\rnscreens.dir\\...).
    # Backslash is not a valid path separator on Linux; AGP regex patterns
    # require forward slashes to identify cmake targets.
    if '\\' in v:
        v = v.replace('\\', '/')
    return v


def _walk_normalize(obj):
    """Recursively walk a parsed JSON object and normalize all string values."""
    if isinstance(obj, str):
        return normalize_str(obj)
    elif isinstance(obj, list):
        return [_walk_normalize(x) for x in obj]
    elif isinstance(obj, dict):
        return {k: _walk_normalize(v) for k, v in obj.items()}
    return obj


def fix_generic_json(raw: bytes) -> bytes:
    """Fix File API reply JSONs — convert W:\\ paths and backslash separators.

    Uses proper JSON parsing so that ALL string values are normalized,
    including relative paths like CMakeFiles\\\\rnscreens.dir\\\\... which
    AGP's CXX1406 target-extraction regex requires to use forward slashes.
    Falls back to regex-only processing if the file is not valid JSON.
    """
    try:
        data = json.loads(raw)
        fixed_data = _walk_normalize(data)
        return json.dumps(fixed_data, indent=2).encode()
    except Exception:
        # Fallback: regex-only for malformed/non-JSON files
        raw = re.sub(rb'W:[/\\]+home[/\\]+', b'/home/', raw)
        raw = re.sub(rb'W:[/\\]+tmp[/\\]+', b'/tmp/', raw)
        raw = re.sub(rb'W:[/\\]+root[/\\]+', b'/root/', raw)
        raw = re.sub(rb'\\\\home\\\\', b'/home/', raw)
        raw = re.sub(rb'\\\\tmp\\\\', b'/tmp/', raw)
        def fix_str(m):
            s = m.group(0)
            return s.replace(b'\\\\', b'/').replace(b'\\/', b'/')
        raw = re.sub(rb'"[^"]*(?:/home/|/tmp/|/root/)[^"]*"', fix_str, raw)
        return raw

def process(build_dir: str):
    fixed = []

    # 1. android_gradle_build.json
    agb = os.path.join(build_dir, 'android_gradle_build.json')
    if os.path.isfile(agb):
        raw = open(agb, 'rb').read()
        try:
            data = json.loads(raw)
            fixed_data = fix_agb(data)
            out = json.dumps(fixed_data, indent=2).encode()
            if out != raw:
                open(agb, 'wb').write(out)
                fixed.append('android_gradle_build.json')
        except Exception as e:
            print(f'  ERROR android_gradle_build.json: {e}', file=sys.stderr)

    # 2. compile_commands.json
    cc = os.path.join(build_dir, 'compile_commands.json')
    if os.path.isfile(cc):
        raw = open(cc, 'rb').read()
        try:
            data = json.loads(raw)
            fixed_data = fix_compile_commands(data)
            out = json.dumps(fixed_data, indent=2).encode()
            if out != raw:
                open(cc, 'wb').write(out)
                fixed.append('compile_commands.json')
        except Exception as e:
            print(f'  ERROR compile_commands.json: {e}', file=sys.stderr)

    # 3. build.ninja — convert backslash path separators to forward slashes.
    #    AGP on Linux reads build.ninja to find object file paths and extract
    #    cmake target names.  Variable assignments like OBJECT_FILE_DIR use
    #    Windows backslash separators which confuse AGP's regex (CXX1406).
    #    ninja.exe and clang.exe on Windows both accept forward slashes, so
    #    this conversion is safe.  rules.ninja (compiler commands) is untouched.
    ninja_file = os.path.join(build_dir, 'build.ninja')
    if os.path.isfile(ninja_file):
        raw = open(ninja_file, 'rb').read()
        # Replace \ with / but preserve ninja line-continuation ($\n) and
        # the literal $ escapes ($$, $:, $ ).  Backslash in build.ninja is
        # only ever used as a Windows path separator — the rule commands that
        # contain shell backslashes live in rules.ninja, which we do not touch.
        if b'\\' in raw:
            out = raw.replace(b'\\', b'/')
            open(ninja_file, 'wb').write(out)
            fixed.append('build.ninja')

    # 4. File API reply JSONs
    reply_dir = os.path.join(build_dir, '.cmake', 'api', 'v1', 'reply')
    if os.path.isdir(reply_dir):
        for fn in os.listdir(reply_dir):
            if fn.endswith('.json'):
                fp = os.path.join(reply_dir, fn)
                raw = open(fp, 'rb').read()
                out = fix_generic_json(raw)
                if out != raw:
                    open(fp, 'wb').write(out)
                    fixed.append(f'reply/{fn}')

    if fixed:
        print(f'  Fixed: {", ".join(fixed)}')
    else:
        print(f'  No changes needed')

if __name__ == '__main__':
    args = sys.argv[1:]
    pre_mode = False
    if args and args[0] == '--pre':
        pre_mode = True
        args = args[1:]
    for d in args:
        if os.path.isdir(d):
            if pre_mode:
                print(f'Pre-processing: {d}')
                preprocess_prefab_cmake(d)
            else:
                print(f'Processing: {d}')
                process(d)
